name: Create Repository from Template

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub username'
        required: true
      repo_name:
        description: 'Repository name (optional, defaults to username-repo)'
        required: false

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create repository from template
        env:
          GITHUB_TOKEN: ${{ secrets.JUSTTOKEN }}
        run: |
          # Inputs
          USERNAME="${{ github.event.inputs.username }}"
          REPO_NAME="${{ github.event.inputs.repo_name }}"
          ORGANIZATION="${{ github.repository_owner }}"
          TEMPLATE_REPO="interview-task" # Replace with your template repo name

          # Default repository name if not provided
          if [ -z "$REPO_NAME" ]; then
            REPO_NAME="${USERNAME}-repo"
          fi

          # Create repository from template
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$ORGANIZATION/$TEMPLATE_REPO/generate \
            -d '{
              "owner": "'"$ORGANIZATION"'",
              "name": "'"$REPO_NAME"'",
              "private": true
            }'
    
      - name: Add user as collaborator
        env:
          GITHUB_TOKEN: ${{ secrets.JUSTTOKEN }}
        run: |
          # Inputs
          USERNAME="${{ github.event.inputs.username }}"
          REPO_NAME="${{ github.event.inputs.repo_name }}"
          ORGANIZATION="${{ github.repository_owner }}"

          # Default repository name if not provided
          if [ -z "$REPO_NAME" ]; then
            REPO_NAME="${USERNAME}-repo"
          fi

          # Add the user as a collaborator with write permission
          curl -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$ORGANIZATION/$REPO_NAME/collaborators/$USERNAME \
            -d '{
              "permission": "push"
            }'

      - name: Done
        run: echo "Repository created from template for ${{ github.event.inputs.username }}"
